#!/usr/bin/env python3
"""Build lantern/cedict-en.tsv from a CC-CEDICT text dump.

Output format, one row per simplified headword, sorted:
    simplified<TAB>traditional<TAB>gloss1; gloss2; gloss3
Glosses are short English senses in CC-CEDICT order, cleaned of parenthetical
notes, pinyin brackets, classifiers and cross-references. At most MAX_SENSES
per row; the runtime filter chooses how many to show.
"""
import argparse
import re
import sys
from collections import OrderedDict

MAX_SENSES = 3

LINE_RE = re.compile(r"^(\S+) (\S+) \[([^\]]*)\] /(.*)/$")
CJK_RE = re.compile(r"[㐀-䶿一-鿿豈-﫿]")
# Senses that are metadata or cross-references rather than meanings.
SKIP_RE = re.compile(
    r"^(variant of|old variant of|erhua variant|Japanese variant|see |see also|"
    r"CL:|also pr\.|also written|also called|also named|abbr\. for|abbr\. of|"
    r"used in|surname |same as |Taiwan pr\.|pr\. )",
    re.I,
)
LEAD_PAREN_RE = re.compile(r"^\([^()]*\)\s*")
TRAIL_PAREN_RE = re.compile(r"\s*\([^()]*\)$")
WHOLE_PAREN_RE = re.compile(r"^\(([^()]*)\)$")
PINYIN_RE = re.compile(r"\[[^\]]*\]")
TRAD_SIMP_PAIR_RE = re.compile(r"(\S+)\|(\S+)")
SPACES_RE = re.compile(r"\s+")


def parse_line(line):
    """Return (trad, simp, pinyin, [sense, ...]) or None for comments/blank."""
    line = line.rstrip("\n")
    if not line or line.startswith("#"):
        return None
    m = LINE_RE.match(line)
    if not m:
        return None
    trad, simp, pinyin, body = m.groups()
    return trad, simp, pinyin, body.split("/")


def split_subsenses(sense):
    return [s for s in sense.split("; ") if s]


def strip_parens(text):
    """Remove leading and trailing parenthetical notes, repeatedly."""
    prev = None
    while prev != text:
        prev = text
        text = LEAD_PAREN_RE.sub("", text)
        text = TRAIL_PAREN_RE.sub("", text)
    return text.strip()


def clean(sub):
    """Clean one sub-sense. Returns (gloss, is_fallback).

    A fallback is a gloss we only use when nothing better exists: the inner
    text of a purely parenthetical sense such as "(completed action marker)",
    or a sense that mentions Chinese characters.
    """
    text = sub.strip()
    whole = WHOLE_PAREN_RE.match(text)
    if whole:
        return SPACES_RE.sub(" ", whole.group(1)).strip(), True
    text = strip_parens(text)
    text = TRAD_SIMP_PAIR_RE.sub(r"\2", text)
    text = PINYIN_RE.sub("", text)
    text = SPACES_RE.sub(" ", text).strip(" ,;")
    if not text:
        return "", True
    if CJK_RE.search(text):
        # Mentions Chinese characters: keep the English remainder as a fallback.
        text = SPACES_RE.sub(" ", CJK_RE.sub("", text)).strip(" ,;")
        return text, True
    return text, False


def glosses_for_entry(senses):
    """Cleaned glosses for one CEDICT entry, best first."""
    good, fallback = [], []
    for sense in senses:
        for sub in split_subsenses(sense):
            if SKIP_RE.match(sub):
                continue
            text, is_fallback = clean(sub)
            if not text:
                continue
            add_glosses(fallback if is_fallback else good, [text])
    return good or fallback[:1]


def add_glosses(existing, new):
    seen = {g.lower() for g in existing}
    for g in new:
        if g.lower() not in seen:
            existing.append(g)
            seen.add(g.lower())


def build(lines):
    """OrderedDict simp -> (trad, [glosses]) from CEDICT lines."""
    table = OrderedDict()
    for line in lines:
        parsed = parse_line(line)
        if not parsed:
            continue
        trad, simp, _pinyin, senses = parsed
        if not CJK_RE.search(simp):
            continue
        glosses = glosses_for_entry(senses)
        if not glosses:
            continue
        if simp in table:
            add_glosses(table[simp][1], glosses)
        else:
            table[simp] = (trad, list(glosses))
    for simp, (trad, glosses) in table.items():
        del glosses[MAX_SENSES:]
    return table


def header_meta(lines):
    meta = {}
    for line in lines:
        if line.startswith("#! "):
            key, _, value = line[3:].partition("=")
            meta[key.strip()] = value.strip()
    return meta


def write_tsv(table, meta, out, sha256=None):
    out.write("# rime-lantern gloss table, generated by tools/build_gloss.py\n")
    out.write("# Source: CC-CEDICT (https://cc-cedict.org), release date "
              f"{meta.get('date', 'unknown')}, {meta.get('entries', '?')} entries\n")
    if sha256:
        out.write(f"# Source sha256: {sha256}\n")
    out.write("# License: CC BY-SA 4.0 (https://creativecommons.org/licenses/by-sa/4.0/)\n")
    out.write("# Columns: simplified<TAB>traditional<TAB>gloss1; gloss2; gloss3\n")
    for simp in sorted(table):
        trad, glosses = table[simp]
        out.write(f"{simp}\t{trad}\t{'; '.join(glosses)}\n")


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("cedict", help="CC-CEDICT text dump (UTF-8, uncompressed)")
    ap.add_argument("out", help="output TSV path, or - for stdout")
    ap.add_argument("--sha256", help="sha256 of the source, recorded in the header")
    args = ap.parse_args(argv)
    with open(args.cedict, encoding="utf-8") as f:
        lines = f.readlines()
    table = build(lines)
    meta = header_meta(lines)
    if args.out == "-":
        write_tsv(table, meta, sys.stdout, args.sha256)
    else:
        with open(args.out, "w", encoding="utf-8") as f:
            write_tsv(table, meta, f, args.sha256)
    print(f"{len(table)} rows from {meta.get('entries', '?')} entries", file=sys.stderr)


if __name__ == "__main__":
    main()
